// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHsdk9pE2lxHxVlcJvQsIlDL_Oej3dN0w',
    appId: '1:723250609605:web:c0503b400d7227e9101fac',
    messagingSenderId: '723250609605',
    projectId: 'blog-app-f4b3d',
    authDomain: 'blog-app-f4b3d.firebaseapp.com',
    storageBucket: 'blog-app-f4b3d.appspot.com',
    measurementId: 'G-DDN6RM0GJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGwKZKuCtop11V_w98liP6Z-Ep2GoutKc',
    appId: '1:723250609605:android:42a83e4dd3055be3101fac',
    messagingSenderId: '723250609605',
    projectId: 'blog-app-f4b3d',
    storageBucket: 'blog-app-f4b3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARhRR7Oo65XE0svPX-s3_D665OK39jJ1w',
    appId: '1:723250609605:ios:3eb93b3317251a1d101fac',
    messagingSenderId: '723250609605',
    projectId: 'blog-app-f4b3d',
    storageBucket: 'blog-app-f4b3d.appspot.com',
    iosClientId: '723250609605-ki5sfcifc1138hhn0fjj1hltmi5nv96e.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARhRR7Oo65XE0svPX-s3_D665OK39jJ1w',
    appId: '1:723250609605:ios:3eb93b3317251a1d101fac',
    messagingSenderId: '723250609605',
    projectId: 'blog-app-f4b3d',
    storageBucket: 'blog-app-f4b3d.appspot.com',
    iosClientId: '723250609605-ki5sfcifc1138hhn0fjj1hltmi5nv96e.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogapp',
  );
}
